version: "3.4"

volumes:
  es-data:

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - 127.0.0.1:5601:5601
    depends_on: 
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    volumes: 
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  suscriber:
    build: ./docker/suscriber
    depends_on: 
      - rabbitmq
    volumes:
      - ./data:/data

  publisher:
    build: ./docker/publisher
    depends_on: 
      - suscriber
    volumes:
      - ./data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 127.0.0.1:15672:15672
    restart: always

  maltrail:
    build: ./docker/maltrail
    volumes:
      - ./data/maltrail:/root/.maltrail
